### ISSUE TITLE
Spencer's pic is stretched

### ISSUE THREAD

**Issue by ssfrr** [ResEnv/resenv-site#5]
(And I'm currently a Masters student, at least until admissions are announced later this month)

Here's a square version:

![portrait by felicite - square](https://cloud.githubusercontent.com/assets/734386/6469691/8405fdce-c1ac-11e4-8711-ccc80a856731.JPG)

**Comment by d0nd3r3k** [comment]
Sweet, Thanks!

**Comment by d0nd3r3k** [comment]
Issue moved to [data entry issues page](https://github.com/ResEnv/resenv-site/issues/4)
